_posts/2014-07-03-post-socratic-social.md, _posts/2014-08-13-post-socratic-social.md, _posts/2014-08-27-post-socratic-social.md, _posts/2014-09-10-post-socratic-social.md, _posts/2014-09-24-post-socratic-social.md, _posts/2014-10-08-post-socratic-social.md
=> Remove post-socratic socials

_posts/2019-04-22-socratic-seminar-91.md
Suggested workflow:
- someone opens a PR for a template page for the Socratic Seminar early in the month
- we all open PRs _against that PR branch_ (in this case against https://github.com/BitDevsNYC/BitDevsNYC.github.io/tree/2019-04-socratic-91) to add our own content, and continue to update those PRs through the month
- a couple of days before the event, we merge the individual content PRs into the template PR, and the template PR into master.
@btsea @wbobeirne thoughts?
=> Add template page for socratic seminar 91

_posts/2013-08-07-socratic-seminar-01.md, _posts/2013-08-21-socratic-seminar-02.md, _posts/2013-09-04-socratic-seminar-03.md, _posts/2013-09-18-socratic-seminar-04.md, _posts/2013-10-01-socratic-seminar-05.md, _posts/2013-10-15-socratic-seminar-06.md, _posts/2013-10-29-socratic-seminar-07.md, _posts/2013-11-12-socratic-seminar-08.md, _posts/2013-11-26-socratic-seminar-09.md, _posts/2013-12-10-socratic-seminar-10.md, _posts/2014-01-14-socratic-seminar-11.md
Added posts for the first 11 meetups. I've done some cleanup of the material, but some more could be done later. There aren't any links, but those can also be added later.
=> Add first 11 meetups

_posts/2019-04-22-socratic-seminar-91.md
Open PRs against branch https://github.com/BitDevsNYC/BitDevsNYC.github.io/tree/2019-04-socratic-91 or push commits directly to that branch if you want to edit through github. We'll then merge this branch into master a couple of days before the event.
=> Template page for socratic seminar 91

_posts/2019-05-15-socratic-seminar-92-blockchain-week.md
Not ready for merge.
@wbobeirne @btsea please add your content to this PR and then we can merge on Monday.
=> Add socratic 92

_posts/2019-06-13-socratic-seminar.md
Template page added. Do not merge until content has been filled.
=> DO NOT MERGE Add Socratic 93

_posts/2019-06-13-socratic-seminar-93.md
* The clightning qt wallet wasn't working for me, so can't demo
* Added a link to a set of instructions I'll (partially) be going through to demo the soon-to-be-merged watchtowers
* Going to do a proper demo of loop (have only glossed over it in previous meetups)
* Going to cover and demo the upcoming allowance feature in Joule
Hope the shameless self promotion on that last one's ok
=> Changes to the month in lapps for socratic 93

_posts/2019-07-25-socratic-seminar-94.md
DO NOT MERGE UNTIL CONTENT HAS BEEN ENTERED
For now, this PR just contains a skeleton post for the next socratic. Add commits to this branch with content until it is ready for merge a couple of days before the next socratic event.
=> [WIP] Add socratic 94 template

_posts/2019-08-15-socratic-seminar-95.md
DO NOT MERGE UNTIL CONTENT HAS BEEN ENTERED
For now, this PR just contains a skeleton post for the next socratic. Add commits to this branch with content until it is ready for merge a couple of days before the next socratic event.
=> Add Socratic 95 post

_posts/2019-09-16-socratic-seminar-96.md
Do not merge until content is complete
=> Add socratic 96

_posts/2019-10-24-socratic-seminar-97.md
Do not merge until content is complete
=> Add socratic 97

_posts/2019-11-13-socratic-seminar-98.md
=> Add socratic 98

_posts/2019-12-03-socratic-seminar-99.md
Come and party like it's Socratic 99 🎉 
I've added Optech and Bitcoin Core PR links. There should be some more Bitcoin Core PR links before Tuesday.
@andrerfneves are you happy to add c-lightning/LND/eclair PR links? I assume you'd be talking about them. Let me know if you want me to handle them.
=> Add socratic 99

_posts/2020-01-09-socratic-seminar-100.md
=> [WIP] Socratic 100

_posts/2020-01-09-socratic-seminar-100.md, _posts/2020-02-12-socratic-seminar-101.md
Also fix link to meetup for socratic 100
=> Add placeholder page for socratic 101

_posts/2020-02-19-whitepaper-series-11-coinjoin.md
=> coinjoin whitepaper series

_posts/2020-02-12-socratic-seminar-101.md
Do not merge.
@btsea @andrerfneves @jnewbery to add topics before **3pm on Tues Feb 11**. (Set a calendar reminder!)
=> [WIP] Add post for socratic 101

_posts/2020-01-09-socratic-seminar-100.md, _posts/2020-03-04-socratic-seminar-102.md
Do not merge. 
@jnewbery @andrerfneves @btsea Topics by tomorrow at 3PM please!
=> [WIP] Add post for socratic 102

_posts/2020-03-04-running-a-great-socratic-seminar.md
I've just thrown in a bunch of bullet points. We should edit this and make it a bit friendlier.
closes #41
=> [WIP] Add a blog post for "Running a Great Socratic Seminar"

_posts/2020-04-30-solo-socratic-1.md, _posts/2020-05-30-solo-socratic-2.md
Ready for links. I will post a short blurb at the top as well.
=> [WIP] Add post for solo socratic 2

_posts/2021-04-30-solo-socratic-13.md
Includes mailing list posts, optech newsletters and Bitcoin Core/BIP PRs.
=> Add solo socratic 13

_posts/2021-09-11-socratic-seminar-104.md
I just set the date to 09-11 (one month after previous socratic). Obviously update the filename before publishing to get the right date.
=> Add socratic 104

_posts/2022-03-30-contributing-to-the-bitdevs-nyc-newseltter.md
TODO: 
- Clean up and add actual links
- Complete the Submitting Content section
=> [WIP] Contributor blog post

cities.md
You mentioned yesterday that London wasn't on the list
=> Add London

_posts/2022-05-26-socratic-seminar-112.md
Meeting notes for the socratic seminar on 2022-05-26.
=> Add socratic 112

_posts/2022-06-30-socratic-seminar-113.md
=> Add seminar 113 and newsletters

cities.md
Hello! 
I've started a San Juan BitDevs meetup and would love to have it listed on your site on the Cities page. Here is our info...
https://sanjuanbitdevs.org/
https://www.meetup.com/san-juan-bitdevs/
https://twitter.com/SanJuanBitdevs
Cheers
=> Add San Juan to Cities

cities.md
Adding Minneapolis BitDevs link to BitDevs NYC website
=> Add Minneapolis to Cities

_posts/2023-03-29-socratic-seminar-122.md
=> Add soc-122

cities.md
Adding Norfolk, VA to the list of cities.  Let me know if this should specify United States and Virginia because there are several Norfolks.
=> Update cities.md to include Norfolk

cities.md
Victoria Bitdevs active since Jan 2023
=> Updated cities to include Victoria

cities.md
Please add Louisville to the list of cites.
We are holding our first meeting on January 28th and plan to hold meetings on the last Sunday of each month.
=> add Louisville to cites page

cities.md
We are having our 10th meetup [next Tuesday](https://www.meetup.com/blockchaingreece-0/events/301154650/).
=> add Athens to cities

_posts/2024-06-27-bitcoin-developers’-socratic-seminar-137.md
- Update sponsor section to fit event
- Update spelling of Pubkey to match their own website’s spelling
- Remove empty section
=> Update sponsor mention
